Repository jcr7467/UCLAbookstack, pull requests merged in 2020-10, with the labels that each got.

#67 Update Readme
  README.md
Labels: Priority - Low, misc

#73 Issue #71 Conditional Added
  views/error.hbs
Labels: bug

#76 Problem:
  public/css/index.css
  public/css/style.css
  public/css/style.min.css
  public/scss/layouts/footer/_footer-one.scss
  public/scss/pages/_login-page.scss
  views/partials/footers/default-footer.hbs
  views/partials/footers/mobile-footer.hbs
Labels: Priority - Low, styling

#88 Create project_board_automation.yml
  .github/workflows/project_board_automation.yml
Labels: Priority - Low, optimization

#89 Fixed issues #40 and #62
  views/layouts/layout.hbs
Labels: Priority - High, Priority - Medium, bug

#86 Fixed Minor issues in the front end for issue #84 and #85
  middleware/middleware.js
  public/css/index.css
  public/css/index.css.map
  public/css/index.min.css
  public/css/style.css
  public/css/style.css.map
  public/css/style.min.css
  public/scss/index.scss
  views/adminpage.hbs
  views/bookpage.hbs
  views/partials/profile/profile_books.hbs
  views/partials/profile/profile_editbooks.hbs
  views/partials/profile/profile_settings.hbs
  views/partials/profile/profile_uploadbooks.hbs
  views/search_for_books.hbs
Labels: Priority - Low, Priority - Medium, misc, styling
